In [3]:
# Task 1

def convert_length(value, unit):
    if unit == 'm':
        return value * 3.28084, 'ft'
    elif unit == 'ft':
        return value / 3.28084, 'm'
    else:
        raise ValueError("Invalid length unit. Choose 'm' or 'ft'.")

def convert_weight(value, unit):
    if unit == 'kg':
        return value * 2.20462, 'lbs'
    elif unit == 'lbs':
        return value / 2.20462, 'kg'
    else:
        raise ValueError("Invalid weight unit. Choose 'kg' or 'lbs'.")

def convert_volume(value, unit):
    if unit == 'L':
        return value * 0.264172, 'gal'
    elif unit == 'gal':
        return value / 0.264172, 'L'
    else:
        raise ValueError("Invalid volume unit. Choose 'L' or 'gal'.")

def main():
    try:
        print("Choose conversion type: 1. Length 2. Weight 3. Volume")
        choice = input("Enter choice (1/2/3): ")
        
        if choice == '1':
            value = float(input("Enter value to convert: "))
            unit = input("Enter unit (m/ft): ").strip().lower()
            result, result_unit = convert_length(value, unit)
        elif choice == '2':
            value = float(input("Enter value to convert: "))
            unit = input("Enter unit (kg/lbs): ").strip().lower()
            result, result_unit = convert_weight(value, unit)
        elif choice == '3':
            value = float(input("Enter value to convert: "))
            unit = input("Enter unit (L/gal): ").strip().lower()
            result, result_unit = convert_volume(value, unit)
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")
            return
        
        print(f"Converted value: {result:.2f} {result_unit}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Choose conversion type: 1. Length 2. Weight 3. Volume
Converted value: 3280.84 ft


In [4]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def main():
    try:
        print("Choose an operation:")
        print("1. Sum\n2. Average\n3. Maximum\n4. Minimum")
        choice = input("Enter choice (1/2/3/4): ")
        
        numbers = input("Enter a list of numbers separated by spaces: ").split()
        numbers = [float(num) for num in numbers] 
        
        if not numbers:
            raise ValueError("The list cannot be empty.")
        
        if choice == '1':
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == '2':
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == '3':
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == '4':
            result = find_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Sum: 14.0


In [5]:
def extract_every_other(lst):
    return lst[::2]

if __name__ == "__main__":
    lst = [1, 2, 3, 4, 5, 6]
    print("Extracted elements:", extract_every_other(lst))

Extracted elements: [1, 3, 5]


In [6]:
def extract_every_other(lst):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

if __name__ == "__main__":
    lst = [1, 2, 3, 4, 5, 6]
    print("Extracted elements:", extract_every_other(lst))
    print("Sublist:", get_sublist(lst, 2, 4))

Extracted elements: [1, 3, 5]
Sublist: [3, 4, 5]


In [7]:
def extract_every_other(lst):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

def reverse_list(lst):
    return lst[::-1]

if __name__ == "__main__":
    lst = [1, 2, 3, 4, 5, 6]
    print("Extracted elements:", extract_every_other(lst))
    print("Sublist:", get_sublist(lst, 2, 4))
    print("Reversed list:", reverse_list(lst))

Extracted elements: [1, 3, 5]
Sublist: [3, 4, 5]
Reversed list: [6, 5, 4, 3, 2, 1]


In [8]:
def remove_first_last(lst):
    return lst[1:-1]

example_list = [1, 2, 3, 4, 5]
result = remove_first_last(example_list)
print(result)


[2, 3, 4]


In [9]:
def get_first_n(lst, n):
    return lst[:n]

example_list = [1, 2, 3, 4, 5]
n = 3
result = get_first_n(example_list, n)
print(result)


[1, 2, 3]


In [10]:
def get_last_n(lst, n):
    return lst[-n:]

example_list = [1, 2, 3, 4, 5]
n = 2
result = get_last_n(example_list, n)
print(result)

[4, 5]


In [11]:
def reverse_skip(lst):
    return lst[-2::-2]

example_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(example_list)
print(result)

[5, 3, 1]


In [12]:
def flatten(lst):
    return [item for sublist in lst for item in sublist]

nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print(result)


[1, 2, 3, 4, 5]


In [13]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print(result)

6


In [14]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item 
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)

21


In [20]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):
            lst[i] = remove_element(lst[i], elem)
        else:
            if lst[i] == elem:
                lst[i] = None 
    
    lst = [item for item in lst if item is not None]
    return lst

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)
print(result)


[[1], [3], [4, 5]]


In [21]:
def find_max(lst):
    max_element = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_element = max(max_element, find_max(item))
        else:
            max_element = max(max_element, item)
    return max_element

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)

6


In [22]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print(result)

3


In [23]:
def deep_flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)
    return flattened

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


In [29]:
def flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))
        else:
            flattened.append(item)
    return flattened

def average_nested(lst):
    flattened_list = flatten(lst)
    total = sum(flattened_list)
    count = len(flattened_list)
    return total / count if count > 0 else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)


3.5


In [30]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):")
print(empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
shape = (3, 3)
fill_value = 7 
filled_array = np.full(shape, fill_value)
print("\nFilled Array (3x3) with value 7:")
print(filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([1, 2, 3])
zeros_array = np.zeros_like(reference_array)
print("\nArray of Zeros with same shape and type as reference array:")
print(zeros_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nArray of Ones with same shape and type as reference array:")
print(ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted List to Numpy Array:")
print(numpy_array)


Empty Array (2x2):
[[2.41910791e-312 3.44897822e-307]
 [2.11398144e-307 6.89796323e-307]]

All Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array (3x3) with value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of Zeros with same shape and type as reference array:
[0 0 0]

Array of Ones with same shape and type as reference array:
[1 1 1]

Converted List to Numpy Array:
[1 2 3 4]


In [31]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:")
print(arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:")
print(arr2)

# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3x3 Identity Matrix:")
print(arr3)

# 4. Create a random array of size 30 and find the mean of the array
arr4 = np.random.random(30)
mean_value = arr4.mean()
print("\nRandom array of size 30:")
print(arr4)
print(f"Mean of the array: {mean_value}")

# 5. Create a 10x10 array with random values and find the minimum and maximum values
arr5 = np.random.random((10, 10))
min_value = arr5.min()
max_value = arr5.max()
print("\n10x10 Array with random values:")
print(arr5)
print(f"Minimum value: {min_value}, Maximum value: {max_value}")

# 6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\nZero array with 5th element replaced with 1:")
print(arr6)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]
print("\nReversed array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n2D Array with 1 on the border and 0 inside:")
print(arr8)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:")
print(arr9)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
[0.95942641 0.92802106 0.23670586 0.73327893 0.84789339 0.82893229
 0.68121793 0.6788781  0.02442697 0.43332354 0.27130496 0.65424401
 0.96184782 0.09674794 0.98076434 0.98683323 0.7194985  0.86785399
 0.55637664 0.0228883  0.38928958 0.69208027 0.19802633 0.69401894
 0.40296528 0.3138909  0.33907327 0.53963761 0.5801445  0.30165962]
Mean of the array: 0.5640416834182908

10x10 Array with random values:
[[0.62736593 0.5769727  0.43911331 0.50200396 0.06164162 0.55743625
  0.30104668 0.18535268 0.40138548 0.9552598 ]
 [0.8450241  0.63134808 0.69011947 0.37228069 0.78160606 0.34456776
  0.86351223 0.07474686 0.78380433 0.23102439]
 [0.46732046 0.12707618 0.62389237 0.79171214 0.51038833 0.33536177
 

In [32]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
addition_result = x + y
print("Addition of x and y:")
print(addition_result)

# 2. Subtract the two arrays
subtraction_result = x - y
print("\nSubtraction of x and y:")
print(subtraction_result)

# 3. Multiply the array with any integers of your choice
multiplication_result = x * 2
print("\nMultiplication of x with 2:")
print(multiplication_result)

# 4. Find the square of each element of the array
squared_result = np.square(x)
print("\nSquare of each element of x:")
print(squared_result)

# 5. Find the dot product between:
# - v and w
dot_product_v_w = np.dot(v, w)
print("\nDot product between v and w:")
print(dot_product_v_w)

# - x and v
dot_product_x_v = np.dot(x, v)
print("\nDot product between x and v:")
print(dot_product_x_v)

# - x and y
dot_product_x_y = np.dot(x, y)
print("\nDot product between x and y:")
print(dot_product_x_y)

# 6. Concatenate x and y along row and concatenate v and w along column.
concatenate_x_y_row = np.concatenate((x, y), axis=0)
print("\nConcatenating x and y along row:")
print(concatenate_x_y_row)

concatenate_v_w_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("\nConcatenating v and w along column:")
print(concatenate_v_w_column)

# 7. Concatenate x and v; if you get an error, observe and explain why you got the error.
try:
    concatenate_x_v = np.concatenate((x, v), axis=0)
    print("\nConcatenating x and v:")
    print(concatenate_x_v)
except Exception as e:
    print("\nError when concatenating x and v:", e)


Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x with 2:
[[ 2  4]
 [ 6 10]]

Square of each element of x:
[[ 1  4]
 [ 9 25]]

Dot product between v and w:
219

Dot product between x and v:
[29 77]

Dot product between x and y:
[[19 22]
 [50 58]]

Concatenating x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v and w along column:
[[ 9 11]
 [10 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [33]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

I = np.eye(2)

A_inv = np.linalg.inv(A)

# Prove A * A_inv = I
result_1 = np.dot(A, A_inv)
print("A * A_inv = \n", result_1)

AB = np.dot(A, B)
BA = np.dot(B, A)

# Prove AB != BA
print("\nAB = \n", AB)
print("\nBA = \n", BA)

# Prove (AB)^T = B^T * A^T
transpose_AB = np.transpose(AB)
transpose_BA = np.dot(np.transpose(B), np.transpose(A))

print("\n(AB)^T = \n", transpose_AB)
print("\nB^T * A^T = \n", transpose_BA)

A * A_inv = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB = 
 [[23 13]
 [51 29]]

BA = 
 [[36 44]
 [13 16]]

(AB)^T = 
 [[23 51]
 [13 29]]

B^T * A^T = 
 [[23 51]
 [13 29]]


In [34]:
# Solve the system of linear equations using Inverse Methods
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using Inverse Method (X = A_inv * B)
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\nSolution using Inverse Method (X = A_inv * B):")
print("x = ", X[0], ", y = ", X[1], ", z = ", X[2])

# Solve using np.linalg.solve()
X_solved = np.linalg.solve(A_eq, B_eq)
print("\nSolution using np.linalg.solve:")
print("x = ", X_solved[0], ", y = ", X_solved[1], ", z = ", X_solved[2])


Solution using Inverse Method (X = A_inv * B):
x =  2.0 , y =  1.0 , z =  -2.0

Solution using np.linalg.solve:
x =  2.0 , y =  1.0000000000000002 , z =  -2.0
